import { ArrowRight, Check, ChevronLeft } from 'lucide-react';
import { money, type CartItem } from '@/types/shop';

type CheckoutProps = { cart: CartItem[]; total: number; orderPlaced: boolean; onBack: () => void; onComplete: () => void; onHome: () => void };

export default function Checkout({ cart, total, orderPlaced, onBack, onComplete, onHome }: CheckoutProps) {
  if (orderPlaced) return <section className="confirmation section-pad"><div className="confirmation-mark"><Check size={33} /></div><p className="eyebrow">ORDER RECEIVED</p><h1>Thank you for<br /><i>choosing Pure.</i></h1><p>Your order has been received. We'll call you shortly to confirm the delivery details.</p><strong className="order-number">Order number: PL-10024</strong><button className="button button-dark" onClick={onHome}>Back to home <ArrowRight size={17} /></button></section>;
  const delivery = total >= 5000 ? 0 : 150;
  return <section className="checkout-page section-pad"><button className="back-link" onClick={onBack}><ChevronLeft size={17} /> Back to bag</button><div className="checkout-grid"><div><div className="page-intro compact"><p className="eyebrow">ALMOST THERE</p><h1>Delivery <i>details.</i></h1><p>Tell us where to bring your pieces.</p></div><form className="checkout-form" onSubmit={(event) => { event.preventDefault(); onComplete(); }}><div className="form-section"><h3>Contact information</h3><div className="form-row"><label>First name<input required placeholder="Your first name" /></label><label>Last name<input required placeholder="Your last name" /></label></div><label>Email address<input type="email" required placeholder="you@example.com" /></label><label>Phone number<input type="tel" required placeholder="+20 1X XXX XXXX" /></label></div><div className="form-section"><h3>Delivery address</h3><label>Address<input required placeholder="Street and building number" /></label><div className="form-row"><label>City<input required placeholder="Cairo" /></label><label>Area / district<input required placeholder="Maadi" /></label></div><label>Delivery notes <span className="optional">Optional</span><textarea placeholder="Anything we should know?" /></label></div><div className="payment-method"><div className="cod-icon">EGP</div><div><b>Cash on delivery</b><span>Pay when your order arrives. No card required.</span></div><Check size={18} /></div><label className="terms"><input type="checkbox" required /> I agree to the Terms & Conditions</label><button className="button button-dark full" type="submit">Place order <ArrowRight size={17} /></button></form></div><aside className="summary checkout-summary"><h3>Your order</h3>{cart.map(({ product, quantity }) => <div className="mini-product" key={product.id}><img src={product.image} alt="" /><div><b>{product.name}</b><span>Qty {quantity}</span></div><strong>{money(product.price * quantity)}</strong></div>)}<hr /><div><span>Subtotal</span><strong>{money(total)}</strong></div><div><span>Delivery</span><strong>{delivery ? money(delivery) : 'Complimentary'}</strong></div><div className="summary-total"><span>Total</span><strong>{money(total + delivery)}</strong></div></aside></div></section>;
}
