import { ChevronDown, Search } from 'lucide-react';
import { photos } from '@/data/site';
import type { Collection, StoreProduct } from '@/types/shop';
import ProductCard from '@/components/ProductCard';

type ShopProps = { products: StoreProduct[]; collection: Collection; query: string; category: string; onQueryChange: (value: string) => void; onCategoryChange: (value: string) => void; wishlist: string[]; onProduct: (product: StoreProduct) => void; onToggleWishlist: (id: string) => void; onAddToCart: (product: StoreProduct) => void };

export default function Shop({ products, collection, query, category, onQueryChange, onCategoryChange, wishlist, onProduct, onToggleWishlist, onAddToCart }: ShopProps) {
  const filters = ['All products', 'Pendant Lights', 'Chandeliers', 'Wall Lights', 'Ceiling Lights', 'Floor Lamps', 'Audio Systems'];
  const curated = collection !== 'all';
  const title = collection === 'new' ? 'New arrivals.' : 'Best sellers.';
  const kicker = collection === 'new' ? 'JUST IN' : 'LOVED BY MANY';
  const description = collection === 'new' ? 'Fresh forms, warm finishes and the latest pieces to change the mood of a room.' : 'The pieces our customers return to — trusted silhouettes with a lasting glow.';
  return <section className={`shop-page section-pad ${curated ? 'curated-shop-page' : ''}`}>{curated ? <div className="collection-hero" style={{ backgroundImage: `linear-gradient(90deg, #1b241dd9, #1b241d5c), url(${collection === 'new' ? photos.dining : photos.pendant})` }}><div><p className="eyebrow light">{kicker}</p><h1>{title}</h1><p>{description}</p></div><span className="collection-count">{products.length.toString().padStart(2, '0')} pieces<br /><small>in this edit</small></span></div> : <div className="page-intro"><p className="eyebrow">THE COLLECTION</p><h1>All <i>pieces.</i></h1><p>Lighting and technology for spaces that feel as good as they look.</p></div>}{curated ? <div className="curated-toolbar"><div><span>THE EDIT</span><b>{products.length} considered pieces</b></div><div className="shop-search"><Search size={17} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search this edit" /></div></div> : <div className="shop-toolbar"><div className="filter-scroll">{filters.map((filter) => <button className={category === filter ? 'selected' : ''} key={filter} onClick={() => onCategoryChange(filter)}>{filter}</button>)}</div><div className="shop-search"><Search size={17} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search collection" /></div><button className="sort-button">Featured <ChevronDown size={15} /></button></div>} {!curated && <div className="results-line"><span>{products.length} pieces</span><span>Cash on delivery available</span></div>}{products.length ? <div className="product-grid shop-grid">{products.map((product) => <ProductCard key={product.id} product={product} wishlist={wishlist} onProduct={onProduct} onToggleWishlist={onToggleWishlist} onAddToCart={onAddToCart} />)}</div> : <div className="empty-state"><Search size={30} /><h3>No pieces found</h3><p>Try another search or explore the full collection.</p></div>}</section>;
}
